services:
  app:
    build: .
    container_name: TrainNotifierApp
    command: 'python ./main.py'
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - celery_redis

  mongo:
    image: mongo:8.0.3
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 11111
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017

  celery_redis:
    image: redis:alpine
    expose:
      - 6379
    restart: always

  celery_worker:
    build: .
    command: "celery -A mycelery worker -l INFO"
    env_file:
      - .env
    depends_on:
      - celery_redis
      - selenium-driver

  celery_beat:
    build: .
    command: "celery -A mycelery beat -l INFO"
    env_file:
      - .env
    depends_on:
      - celery_redis
      - selenium-driver

  selenium-driver:
    image: selenium/standalone-firefox:latest
    expose:
      - 4444

volumes:
  mongo_data:
