"""initial

Revision ID: b675926c7f3f
Revises: 
Create Date: 2024-11-17 14:31:24.938770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b675926c7f3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from', sa.String(), nullable=False),
    sa.Column('to', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('trip_time', sa.Time(), nullable=False),
    sa.Column('departure_datetime', sa.DateTime(), nullable=False),
    sa.Column('arrival_datetime', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'AVAILABLE', name='trainstatus'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_routes',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'route_id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('vertical_shelf_placement', sa.Enum('TOP', 'BOTTOM', name='vertical_shelf_placement'), nullable=False),
    sa.Column('horisontal_shelf_placement', sa.Enum('TOP', 'BOTTOM', name='horisontal_shelf_placement'), nullable=False),
    sa.Column('carriage_type', sa.Enum('REVERSED_SEAT', 'COUPE', name='carriage_type'), nullable=False),
    sa.Column('train_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['train_id'], ['train.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('user_routes')
    op.drop_table('train')
    op.drop_table('route')
    # ### end Alembic commands ###
