"""empty message

Revision ID: 28cfbec4758d
Revises: 51868e6d8e34
Create Date: 2024-11-24 13:48:05.007597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28cfbec4758d'
down_revision: Union[str, None] = '51868e6d8e34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_route_for_every_service', 'route', ['from', 'to', 'date', 'railway_ticket_service'])
    op.alter_column('train', 'trip_time',
               existing_type=postgresql.TIME(),
               type_=sa.Interval(),
               existing_nullable=False)
    op.create_unique_constraint('unique_train_for_every_route', 'train', ['number', 'route_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_train_for_every_route', 'train', type_='unique')
    op.alter_column('train', 'trip_time',
               existing_type=sa.Interval(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.drop_constraint('unique_route_for_every_service', 'route', type_='unique')
    # ### end Alembic commands ###
