"""new changes

Revision ID: 51868e6d8e34
Revises: b675926c7f3f
Create Date: 2024-11-22 09:06:55.538104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51868e6d8e34'
down_revision: Union[str, None] = 'b675926c7f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

railway_ticket_service_enum = postgresql.ENUM('TUTURU', name='railwayticketservices', create_type=False)

old_vertical_enum = postgresql.ENUM('TOP', 'BOTTOM', name='vertical_shelf_placement', create_type=False)
new_vertical_enum = sa.Enum('TOP', 'BOTTOM', name='verticalshelfplacement', create_type=False)

old_horizontal_enum = postgresql.ENUM('TOP', 'BOTTOM', name='horisontal_shelf_placement', create_type=False)
new_horizontal_enum = sa.Enum('TOP', 'BOTTOM', name='horisontalshelfplacement', create_type=False)

old_carriage_enum = postgresql.ENUM('REVERSED_SEAT', 'COUPE', name='carriage_type', create_type=False)
new_carriage_enum = sa.Enum('REVERSED_SEAT', 'COUPE', name='carriagetype', create_type=False)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    railway_ticket_service_enum.create(bind)
    op.add_column('route', sa.Column('railway_ticket_service', railway_ticket_service_enum, nullable=False))

    new_vertical_enum.create(bind)
    new_horizontal_enum.create(bind)
    new_carriage_enum.create(bind)

    op.execute(
        "ALTER TABLE ticket ALTER COLUMN vertical_shelf_placement TYPE verticalshelfplacement "
        "USING vertical_shelf_placement::text::verticalshelfplacement"
    )
    op.execute(
        "ALTER TABLE ticket ALTER COLUMN horisontal_shelf_placement TYPE horisontalshelfplacement "
        "USING horisontal_shelf_placement::text::horisontalshelfplacement"
    )
    op.execute(
        "ALTER TABLE ticket ALTER COLUMN carriage_type TYPE carriagetype "
        "USING carriage_type::text::carriagetype"
    )
    op.alter_column('route', 'date',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.Date(),
                    existing_nullable=False)
    op.alter_column('train', 'url',
                    existing_type=sa.VARCHAR(),
                    nullable=True)

    old_vertical_enum.drop(bind)
    old_horizontal_enum.drop(bind)
    old_carriage_enum.drop(bind)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    old_vertical_enum.create(bind)
    old_horizontal_enum.create(bind)
    old_carriage_enum.create(bind)

    op.execute(
        "ALTER TABLE ticket ALTER COLUMN vertical_shelf_placement TYPE vertical_shelf_placement "
        "USING vertical_shelf_placement::text::vertical_shelf_placement"
    )
    op.execute(
        "ALTER TABLE ticket ALTER COLUMN horisontal_shelf_placement TYPE horisontal_shelf_placement "
        "USING horisontal_shelf_placement::text::horisontal_shelf_placement"
    )
    op.execute(
        "ALTER TABLE ticket ALTER COLUMN carriage_type TYPE carriage_type "
        "USING carriage_type::text::carriage_type"
    )
    new_vertical_enum.drop(bind)
    new_horizontal_enum.drop(bind)
    new_carriage_enum.drop(bind)

    op.alter_column('route', 'date',
                    existing_type=sa.Date(),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False)
    op.drop_column('route', 'railway_ticket_service')
    railway_ticket_service_enum.drop(bind)
    op.alter_column('train', 'url',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    # ### end Alembic commands ###
